apiVersion: v1
kind: List
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app.kubernetes.io/name: hello-java-spring-boot
    name: hello-java-spring-boot
  spec:
    output:
      to:
        kind: DockerImage
        name: docker.io/robekson2020/demo:1.0.0
    source:
      # Expect a local directory to be streamed to OpenShift as a build source
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy:
        # Find the image build instructions in ./Dockerfile
        dockerfilePath: Dockerfile
